[package]
name = "deno_notify"
version = "0.4.5"
authors = ["Pandawan <pandawanfr@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.13"
deno_core = "0.83.0"
notify-rust = "4.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
